import Colors from "./Colors";

export default {
  h1: {
    marginTop: 16,
    color: Colors.rouge,
    fontSize: 46,
    fontFamily: "Seraya-Display",
    textAlign: "left",
  },
  h2: {
    fontSize: 24,
    textAlign: "center",
    color: Colors.blanc,
    marginVertical: 16,
    fontFamily: "IvyMode-Bold",
    opacity: 0.9,
  },
  h3: {
    fontSize: 16,
    fontWeight: "500",
    color: Colors.blanc,
    fontFamily: "IvyMode-SemiBold",
    opacity: 0.9,
  },
  p: {
    fontSize: 16,
    fontWeight: "400",
    color: Colors.or,
    fontFamily: "SFPro-Regular",
    maxWidth: 1000,
    opacity: 0.8,
  },
  underText: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "IvyMode-Regular",
    color: Colors.blanc,
    opacity: 0.6,
  },
  bottomText: {
    fontSize: 14,
    paddingVertical: 2,
    color: Colors.blanc,
    fontFamily: "IvyMode-Regular",
    opacity: 0.6,
  },
  imgAlbum: {
    resizeMode: "contain",
    alignSelf: "center",
    width: 200,
    height: 200,
  },
  festival: {
    fontSize: 18,
    fontWeight: "700",
    color: Colors.blanc,
    marginVertical: 6,
  },
  lieu: {
    fontSize: 32,
    fontWeight: "700",
    color: Colors.blanc,
  },
  ville: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.or,
  },
  date: {
    fontSize: 14,
    fontWeight: "400",
    color: Colors.blanc,
    paddingVertical: 6,
  },
  imgConcert: {
    resizeMode: "contain",
    alignSelf: "center",
    width: 200,
    height: 200,
  },
  button: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginLeft: 16,
    marginBottom: 32,
  },
  buttonContent: {
    fontSize: 18,
    marginRight: 16,
    color: Colors.blanc,
  },
};
